name: techtutorpro
description: "A modern, feature-rich mobile learning platform built with Flutter. TechTutor Pro provides seamless course browsing, purchasing, and interactive learning experiences with Material Design 3."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_markdown: ^0.7.4+3
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  injectable: ^2.4.2
  intl: ^0.20.2
  lottie: ^3.1.3
  open_file_plus: ^3.4.1+1
  path_provider: ^2.1.4
  percent_indicator: ^4.2.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  youtube_player_flutter: 9.0.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-techtutorpro.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/dummy/

flutter_native_splash:
  color: "#5A67D8"
  image: assets/images/logo-techtutorpro.jpg
  android: true
  ios: true
